spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: authentication-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

server:
  port: 8089
